[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jls-translator"
version = "1.1.1"
description = "Translate Minecraft Bedrock .lang files into all languages supported by Minecraft. Needs deep-translator and latest python version."
dependencies = [
    "deep-translator",
]

[project.scripts]
jls-translator = "translator.translator:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["translator*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.lang", "*.txt"]