[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jls-translator"
version = "0.0.0"
description = "This branch is only for experimental testing, do not use ———— it may be incredibly unstable!"
dependencies = [
    "deep-translator",
]

[project.scripts]
jls-translator = "translator.translator:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["translator*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.lang", "*.txt"]
